server:
  port: 8766
spring:
  application:
    name: sleuth-8866
eureka:
  client:
    service-url:
      defalut-zone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost

    
